name: 🐛 Bug Report
description: Report a bug or issue with MAX Video Downloader
title: "[Bug] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below to help us fix it.

  - type: checkboxes
    id: checklist
    attributes:
      label: "Pre-submission checklist"
      options:
        - label: "I have searched existing issues to make sure this hasn't been reported before"
          required: true
        - label: "I have tried the basic troubleshooting steps in the [troubleshooting guide](https://github.com/Suwot/max-video-downloader/blob/main/docs/troubleshooting.md)"
          required: true
        - label: "I have tested this in incognito/private browsing mode"
          required: false

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is"
      placeholder: "Describe what happened and what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      description: "Tell us how to reproduce this behavior"
      placeholder: |
        1. Go to website...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: "Website URL"
      description: "What website were you trying to download from? (if applicable)"
      placeholder: "https://example.com/video-page"

  - type: dropdown
    id: browser
    attributes:
      label: "Browser"
      description: "Which browser are you using?"
      options:
        - Chrome
        - Firefox
        - Edge
        - Brave
        - Opera
        - Arc
        - Other (specify in description)
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: "Browser Version"
      description: "What version of the browser? (found in browser settings → about)"
      placeholder: "e.g. 120.0.6099.129"

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: "What operating system are you using?"
      options:
        - macOS
        - Windows
        - Linux
        - Other (specify in description)
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: "OS Version"
      description: "What version of your operating system?"
      placeholder: "e.g. macOS 14.2, Windows 11, Ubuntu 22.04"

  - type: input
    id: extension-version
    attributes:
      label: "Extension Version"
      description: "What version of MAX Video Downloader? (found in browser extensions page)"
      placeholder: "e.g. 0.5.1"

  - type: input
    id: native-version
    attributes:
      label: "Native Host Version"
      description: "What version of the native host? (run `mvdcoapp -version` in terminal)"
      placeholder: "e.g. 0.1.0"

  - type: dropdown
    id: connection-status
    attributes:
      label: "Native Host Connection"
      description: "What does the extension popup show for native host status?"
      options:
        - "Connected (green)"
        - "Disconnected (red)"
        - "Not installed"
        - "Unknown/Other"

  - type: textarea
    id: error-messages
    attributes:
      label: "Error Messages"
      description: "Any error messages you see (screenshots are helpful)"
      placeholder: "Paste any error messages here"

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here"
      placeholder: "Screenshots, logs, or other relevant information"
